node{
  def app
  
  stage('Clone') {
    checkout scm
  }
  
  stage('Build image') {
    app = docker.build("4dvop-image", "./simple_api/")
  }
  
  stage('Test image') {
    docker.image('my_image').withRun("--name mycont -p 5000:5000 -e DEBUG=true"){c ->
      sh 'docker ps'
    
    }
  }
}
