node{
  def app
  
  stage('Clone') {
    checkout scm
  }
  
  stage('Build image') {
    app = docker.build("my_image", "./simple_api/")
  }
  
  stage('Test image') {
    docker.image('my_image').withRun("--name my_test -p 8080:8080"){c ->
      sh 'docker ps'
      sh 'docker inspect my_test | grep "IPAddress"'
      sh 'curl -u toto:python -X GET http://172.17.0.2:8080/pozos/api/v1.0/get_student_ages'
      
    }
  }
}
