- hosts: app_vm
  become: true
  tasks:
    - name: Deploy 4dvop-app
      docker_container:
        name: Api
        hostname: python
        image: nhady/docker-test
        state: started
        ports:
          - "5000:5000"
