- hosts: app_vm
  become: true
  tasks:
    - name: Deploy student-list
      docker_container:
        name: myimage
        hostname: centos
        image: nhady/docker-test
        state: started
        
